// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using terraria_api.Models;

#nullable disable

namespace terraria_api.Migrations
{
    [DbContext(typeof(TerrariaContext))]
    partial class TerrariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");
#pragma warning restore 612, 618
        }
    }
}
